export const ENV = {
  EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || '',
  EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || '',
  EMAILJS_TEMPLATE_ID_FEEDBACK: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_FEEDBACK || '',
  EMAILJS_TEMPLATE_ID_SUBSCRIPTION: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_SUBSCRIPTION || '',
};
