nodeLinker: node-modules

packageExtensions:
  'eslint-config-airbnb@*':
    dependencies:
      'eslint-plugin-react': '*'
      'eslint-plugin-react-hooks': '*'
  '@typescript-eslint/utils@*':
    dependencies:
      'eslint': '*'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
