nodeLinker: node-modules

packageExtensions:
  'eslint-config-airbnb@*':
    dependencies:
      'eslint-plugin-react': '*'
      'eslint-plugin-react-hooks': '*'
  '@typescript-eslint/utils@*':
    dependencies:
      'eslint': '*'
